### ISSUE TITLE
URL Request

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [lolPants/retrotext#3]
Hi ,i want to make a RetroText Android app based on your project , so can you please give the full URL request 
`http://photofunia.com/categories/all_effects/retro-wave?server=${server}` ,how i can pass the 3 texts (top middle and bottom) ?

**Comment by lolPants** [comment]
You need to send the request as an HTTP POST with an `application/x-www-form-urlencoded` body.

Here is the relevant form building code.
https://github.com/lolPants/retrotext/blob/bd6e910a2f7a189b952bf53556f865117e511e75/src/index.js#L150-L155
